name: ONE_PIECE_DECK_BUILDER_FRONT_PIPELINE
on:
  push:
    branches:
      - master
      - '*'
jobs:
  build:
    name: Build
    if: github.ref != 'refs/heads/master'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          push: false
  build_push:
    name: Build and Push
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    environment: PROD
    steps:
      - uses: actions/checkout@v2
      - name: Modify environment.prod.ts
        run: |
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "production: true," >> src/environments/environment.prod.ts
          echo "apiUrl: 'https://one-piece-card-game-deck-builder.com/api/'," >> src/environments/environment.prod.ts
          echo "clientId: '${{ secrets.OAUTH_CLIENT_ID }}'" >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jonathanjusseaume/one-piece-deck-builder-front:latest
  deploy_prod:
    name: Deploy Prod
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    needs: build_push
    environment: PROD
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            sudo docker stop front || true && sudo docker rm front || true
            sudo docker pull jonathanjusseaume/one-piece-deck-builder-front:latest
            sudo docker run -d -p 4200:4200 --name front --network=host jonathanjusseaume/one-piece-deck-builder-front:latest

